# This is a basic workflow to help you get started with Actions

name: CI run when tag is pushed

# Controls when the workflow will run
on:
  push:
    tags:
      - v* 
env:
  TZ: Asia/Shanghai


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo github.ref: ${{github.ref}}
          echo github.ref_name: ${{github.ref_name}}
          script_dir=$(dirname $(readlink -f $0))
          echo script_dir: ${{script_dir}}
